	# dyLens slopes
python Distribution_density_slope.py ./7//model4/normal/shear/dyLens/phase5/Analysis_2.5Reff/
python Distribution_density_slope.py ./8//model4/normal/shear/dyLens/phase5/Analysis_2.5Reff/
python Distribution_density_slope.py ./9//model4/normal/shear/dyLens/phase5/Analysis_2.5Reff/
python Distribution_density_slope.py ./11//model4/normal/shear/dyLens/phase5/Analysis_2.5Reff/
python Distribution_density_slope.py ./20//model4/normal/shear/dyLens/phase5/Analysis_2.5Reff/
python Distribution_density_slope.py ./56405//model4/normal/shear/dyLens/phase5/Analysis_2.5Reff/
python Distribution_density_slope.py ./56406//model4/normal/shear/dyLens/phase5/Analysis_2.5Reff/
python Distribution_density_slope.py ./83991//model4/normal/shear/dyLens/phase5/Analysis_2.5Reff/
python Distribution_density_slope.py ./83996//model4/normal/shear/dyLens/phase5/Analysis_2.5Reff/
python Distribution_density_slope.py ./84010//model4/normal/shear/dyLens/phase5/Analysis_2.5Reff/
python Distribution_density_slope.py ./100675//model4/normal/shear/dyLens/phase5/Analysis_2.5Reff/
python Distribution_density_slope.py ./116278//model4/normal/shear/dyLens/phase5/Analysis_2.5Reff/
python Distribution_density_slope.py ./172209//model4/normal/shear/dyLens/phase5/Analysis_2.5Reff/
python Distribution_density_slope.py ./313415//model4/normal/shear/dyLens/phase5/Analysis_2.5Reff/
python Distribution_density_slope.py ./341482//model4/normal/shear/dyLens/phase5/Analysis_2.5Reff/
python Distribution_density_slope.py ./344595//model4/normal/shear/dyLens/phase5/Analysis_2.5Reff/
python Distribution_density_slope.py ./396742//model4/normal/shear/dyLens/phase5/Analysis_2.5Reff/
python Distribution_density_slope.py ./414107//model4/normal/shear/dyLens/phase5/Analysis_2.5Reff/
python Distribution_density_slope.py ./451938//model4/normal/shear/dyLens/phase5/Analysis_2.5Reff/
python Distribution_density_slope.py ./485608//model4/normal/shear/dyLens/phase5/Analysis_2.5Reff/
python Distribution_density_slope.py ./545285//model4/normal/shear/dyLens/phase5/Analysis_2.5Reff/

	# JAM slopes
python Distribution_density_slope.py ./7//model4/normal//JAM/Analysis_2.5Reff/
python Distribution_density_slope.py ./8//model4/normal//JAM/Analysis_2.5Reff/
python Distribution_density_slope.py ./9//model4/normal//JAM/Analysis_2.5Reff/
python Distribution_density_slope.py ./11//model4/normal//JAM/Analysis_2.5Reff/
python Distribution_density_slope.py ./20//model4/normal//JAM/Analysis_2.5Reff/
python Distribution_density_slope.py ./56405//model4/normal//JAM/Analysis_2.5Reff/
python Distribution_density_slope.py ./56406//model4/normal//JAM/Analysis_2.5Reff/
python Distribution_density_slope.py ./83991//model4/normal//JAM/Analysis_2.5Reff/
python Distribution_density_slope.py ./83996//model4/normal//JAM/Analysis_2.5Reff/
python Distribution_density_slope.py ./84010//model4/normal//JAM/Analysis_2.5Reff/
python Distribution_density_slope.py ./100675//model4/normal//JAM/Analysis_2.5Reff/
python Distribution_density_slope.py ./116278//model4/normal//JAM/Analysis_2.5Reff/
python Distribution_density_slope.py ./172209//model4/normal//JAM/Analysis_2.5Reff/
python Distribution_density_slope.py ./313415//model4/normal//JAM/Analysis_2.5Reff/
python Distribution_density_slope.py ./341482//model4/normal//JAM/Analysis_2.5Reff/
python Distribution_density_slope.py ./344595//model4/normal//JAM/Analysis_2.5Reff/
python Distribution_density_slope.py ./396742//model4/normal//JAM/Analysis_2.5Reff/
python Distribution_density_slope.py ./414107//model4/normal//JAM/Analysis_2.5Reff/
python Distribution_density_slope.py ./451938//model4/normal//JAM/Analysis_2.5Reff/
python Distribution_density_slope.py ./485608//model4/normal//JAM/Analysis_2.5Reff/
python Distribution_density_slope.py ./545285//model4/normal//JAM/Analysis_2.5Reff/
