	# dyLens slopes
python Distribution_density_slope.py ./7//model2/normal/shear/dyLens/phase5/Analysis_2.5Reff/
python Distribution_density_slope.py ./8//model2/normal/shear/dyLens/phase5/Analysis_2.5Reff/
python Distribution_density_slope.py ./9//model2/normal/shear/dyLens/phase5/Analysis_2.5Reff/
python Distribution_density_slope.py ./11//model2/normal/shear/dyLens/phase5/Analysis_2.5Reff/
python Distribution_density_slope.py ./20//model2/normal/shear/dyLens/phase5/Analysis_2.5Reff/
python Distribution_density_slope.py ./56405//model2/normal/shear/dyLens/phase5/Analysis_2.5Reff/
python Distribution_density_slope.py ./56406//model2/normal/shear/dyLens/phase5/Analysis_2.5Reff/
python Distribution_density_slope.py ./83991//model2/normal/shear/dyLens/phase5/Analysis_2.5Reff/
python Distribution_density_slope.py ./83996//model2/normal/shear/dyLens/phase5/Analysis_2.5Reff/
python Distribution_density_slope.py ./84010//model2/normal/shear/dyLens/phase5/Analysis_2.5Reff/
python Distribution_density_slope.py ./100675//model2/normal/shear/dyLens/phase5/Analysis_2.5Reff/
python Distribution_density_slope.py ./116278//model2/normal/shear/dyLens/phase5/Analysis_2.5Reff/
python Distribution_density_slope.py ./172209//model2/normal/shear/dyLens/phase5/Analysis_2.5Reff/
python Distribution_density_slope.py ./313415//model2/normal/shear/dyLens/phase5/Analysis_2.5Reff/
python Distribution_density_slope.py ./341482//model2/normal/shear/dyLens/phase5/Analysis_2.5Reff/
python Distribution_density_slope.py ./344595//model2/normal/shear/dyLens/phase5/Analysis_2.5Reff/
python Distribution_density_slope.py ./396742//model2/normal/shear/dyLens/phase5/Analysis_2.5Reff/
python Distribution_density_slope.py ./414107//model2/normal/shear/dyLens/phase5/Analysis_2.5Reff/
python Distribution_density_slope.py ./451938//model2/normal/shear/dyLens/phase5/Analysis_2.5Reff/
python Distribution_density_slope.py ./485608//model2/normal/shear/dyLens/phase5/Analysis_2.5Reff/
python Distribution_density_slope.py ./545285//model2/normal/shear/dyLens/phase5/Analysis_2.5Reff/

	# JAM slopes
python Distribution_density_slope.py ./7//model2/normal//JAM/Analysis_2.5Reff/
python Distribution_density_slope.py ./8//model2/normal//JAM/Analysis_2.5Reff/
python Distribution_density_slope.py ./9//model2/normal//JAM/Analysis_2.5Reff/
python Distribution_density_slope.py ./11//model2/normal//JAM/Analysis_2.5Reff/
python Distribution_density_slope.py ./20//model2/normal//JAM/Analysis_2.5Reff/
python Distribution_density_slope.py ./56405//model2/normal//JAM/Analysis_2.5Reff/
python Distribution_density_slope.py ./56406//model2/normal//JAM/Analysis_2.5Reff/
python Distribution_density_slope.py ./83991//model2/normal//JAM/Analysis_2.5Reff/
python Distribution_density_slope.py ./83996//model2/normal//JAM/Analysis_2.5Reff/
python Distribution_density_slope.py ./84010//model2/normal//JAM/Analysis_2.5Reff/
python Distribution_density_slope.py ./100675//model2/normal//JAM/Analysis_2.5Reff/
python Distribution_density_slope.py ./116278//model2/normal//JAM/Analysis_2.5Reff/
python Distribution_density_slope.py ./172209//model2/normal//JAM/Analysis_2.5Reff/
python Distribution_density_slope.py ./313415//model2/normal//JAM/Analysis_2.5Reff/
python Distribution_density_slope.py ./341482//model2/normal//JAM/Analysis_2.5Reff/
python Distribution_density_slope.py ./344595//model2/normal//JAM/Analysis_2.5Reff/
python Distribution_density_slope.py ./396742//model2/normal//JAM/Analysis_2.5Reff/
python Distribution_density_slope.py ./414107//model2/normal//JAM/Analysis_2.5Reff/
python Distribution_density_slope.py ./451938//model2/normal//JAM/Analysis_2.5Reff/
python Distribution_density_slope.py ./485608//model2/normal//JAM/Analysis_2.5Reff/
python Distribution_density_slope.py ./545285//model2/normal//JAM/Analysis_2.5Reff/
