	# dyLens slopes
python Distribution_density_slope.py ./7//model3/normal/shear/dyLens/phase5/Analysis_2.5Reff/
python Distribution_density_slope.py ./8//model3/normal/shear/dyLens/phase5/Analysis_2.5Reff/
python Distribution_density_slope.py ./9//model3/normal/shear/dyLens/phase5/Analysis_2.5Reff/
python Distribution_density_slope.py ./11//model3/normal/shear/dyLens/phase5/Analysis_2.5Reff/
python Distribution_density_slope.py ./20//model3/normal/shear/dyLens/phase5/Analysis_2.5Reff/
python Distribution_density_slope.py ./56405//model3/normal/shear/dyLens/phase5/Analysis_2.5Reff/
python Distribution_density_slope.py ./56406//model3/normal/shear/dyLens/phase5/Analysis_2.5Reff/
python Distribution_density_slope.py ./83991//model3/normal/shear/dyLens/phase5/Analysis_2.5Reff/
python Distribution_density_slope.py ./83996//model3/normal/shear/dyLens/phase5/Analysis_2.5Reff/
python Distribution_density_slope.py ./84010//model3/normal/shear/dyLens/phase5/Analysis_2.5Reff/
python Distribution_density_slope.py ./100675//model3/normal/shear/dyLens/phase5/Analysis_2.5Reff/
python Distribution_density_slope.py ./116278//model3/normal/shear/dyLens/phase5/Analysis_2.5Reff/
python Distribution_density_slope.py ./172209//model3/normal/shear/dyLens/phase5/Analysis_2.5Reff/
python Distribution_density_slope.py ./313415//model3/normal/shear/dyLens/phase5/Analysis_2.5Reff/
python Distribution_density_slope.py ./341482//model3/normal/shear/dyLens/phase5/Analysis_2.5Reff/
python Distribution_density_slope.py ./344595//model3/normal/shear/dyLens/phase5/Analysis_2.5Reff/
python Distribution_density_slope.py ./396742//model3/normal/shear/dyLens/phase5/Analysis_2.5Reff/
python Distribution_density_slope.py ./414107//model3/normal/shear/dyLens/phase5/Analysis_2.5Reff/
python Distribution_density_slope.py ./451938//model3/normal/shear/dyLens/phase5/Analysis_2.5Reff/
python Distribution_density_slope.py ./485608//model3/normal/shear/dyLens/phase5/Analysis_2.5Reff/
python Distribution_density_slope.py ./545285//model3/normal/shear/dyLens/phase5/Analysis_2.5Reff/

	# JAM slopes
python Distribution_density_slope.py ./7//model3/normal//JAM/Analysis_2.5Reff/
python Distribution_density_slope.py ./8//model3/normal//JAM/Analysis_2.5Reff/
python Distribution_density_slope.py ./9//model3/normal//JAM/Analysis_2.5Reff/
python Distribution_density_slope.py ./11//model3/normal//JAM/Analysis_2.5Reff/
python Distribution_density_slope.py ./20//model3/normal//JAM/Analysis_2.5Reff/
python Distribution_density_slope.py ./56405//model3/normal//JAM/Analysis_2.5Reff/
python Distribution_density_slope.py ./56406//model3/normal//JAM/Analysis_2.5Reff/
python Distribution_density_slope.py ./83991//model3/normal//JAM/Analysis_2.5Reff/
python Distribution_density_slope.py ./83996//model3/normal//JAM/Analysis_2.5Reff/
python Distribution_density_slope.py ./84010//model3/normal//JAM/Analysis_2.5Reff/
python Distribution_density_slope.py ./100675//model3/normal//JAM/Analysis_2.5Reff/
python Distribution_density_slope.py ./116278//model3/normal//JAM/Analysis_2.5Reff/
python Distribution_density_slope.py ./172209//model3/normal//JAM/Analysis_2.5Reff/
python Distribution_density_slope.py ./313415//model3/normal//JAM/Analysis_2.5Reff/
python Distribution_density_slope.py ./341482//model3/normal//JAM/Analysis_2.5Reff/
python Distribution_density_slope.py ./344595//model3/normal//JAM/Analysis_2.5Reff/
python Distribution_density_slope.py ./396742//model3/normal//JAM/Analysis_2.5Reff/
python Distribution_density_slope.py ./414107//model3/normal//JAM/Analysis_2.5Reff/
python Distribution_density_slope.py ./451938//model3/normal//JAM/Analysis_2.5Reff/
python Distribution_density_slope.py ./485608//model3/normal//JAM/Analysis_2.5Reff/
python Distribution_density_slope.py ./545285//model3/normal//JAM/Analysis_2.5Reff/
